const DB_CONTENT_TYPES = {
	DEBOT: 'debot',
}

const COMPONENTS_BINDINGS = {
	TEXT: 'Text',
	INPUT: 'Input',
	TEXTAREA: 'Textarea',
	AMOUNT_INPUT: 'AmountInput',
	CONFIRM_INPUT: 'ConfirmInput',
	MENU: 'Menu',
}

const DEBOT_ADDRESS_SEARCH_PARAM = 'debotAddress';

const DEBOT_WC = -31;
const MNEMONIC_WORD_COUNT = 12;
const DERIVATION_PATH = "m/44'/396'/0'/0/0";

module.exports = {
	DB_CONTENT_TYPES,
	COMPONENTS_BINDINGS,
	DEBOT_ADDRESS_SEARCH_PARAM,
	DEBOT_WC,
	MNEMONIC_WORD_COUNT,
	DERIVATION_PATH,
}
